# Generated by Django 2.2.9 on 2020-04-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200418_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Group name'),
        ),
    ]
